[tool.poetry]
name = "cryptofeed-werks"
version = "0.1.1"
description = "Pipeline for live data from cryptocurrency exchanges"
authors = ["Alex <globophobe@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/globophobe/cryptofeed-werks"
repository = "https://github.com/globophobe/cryptofeed-werks"
keywords = ["cryptocurrency", "trading"]
classifiers = [
    "Operating System :: OS Independent",
]
packages = [{ include = "cryptofeed_werks" }]

[tool.poetry.dependencies]
python = ">=3.7.1, <3.10"
numpy = "^1.21.4"
google-cloud-bigquery = { version = "^2.6.1", optional = true }
google-cloud-bigquery-storage = { version = "^2.1.0", optional = true }
google-cloud-pubsub = { version = "^2.8.0", optional = true }
google-cloud-firestore = { version = "^2.1.0", optional = true }
sentry-sdk = { version = "^1.0.0", optional = true }
cryptofeed = "^2.1.2"
python-decouple = "^3.5"

[tool.poetry.dev-dependencies]
black = "^21.4b0"
pytest = "^6.2.3"
isort = "^5.8.0"
pytest-httpx = "^0.11.0"
flake8 = "^3.9.1"
typer = "^0.3.2"
invoke = "^1.5.0"

[tool.poetry.extras]
all = ["google-cloud-bigquery", "google-cloud-bigquery-storage", "google-cloud-pubsub", "google-cloud-firestore", "sentry-sdk"]
bigquery = ["google-cloud-bigquery", "google-cloud-bigquery-storage"]
firestore = ["google-cloud-firestore"]
sentry = ["sentry-sdk"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
